FROM centos

RUN yum install httpd -y

WORKDIR /var/www/html

COPY frontend .


RUN echo "$(whoami)" > /var/www/html/user1.html

RUN useradd josearangos

USER josearangos

RUN echo "$(whoami)" > /tmp/user2.html

USER root

RUN cp /tmp/user2.html /var/www/html/user2.html

COPY run.sh /run.sh

CMD sh /run.sh
